apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: sock-shop
data:
  Caddyfile: |
    {
        admin 0.0.0.0:2019
        servers {
            metrics
        }
    }

    :8080 {
        reverse_proxy 127.0.0.1:8079
    }
