apiVersion: batch/v1
kind: Job
metadata:
  name: load-generator
  namespace: sock-shop
spec:
  activeDeadlineSeconds: 300
  template:
    spec:
      containers:
      - name: hey
        image: alpine
        command:
        - "/bin/sh"
        - "-c"
        - "apk add --no-cache curl && while true; do curl -s http://front-end.sock-shop.svc.cluster.local/ > /dev/null; sleep 0.1; done"
      restartPolicy: Never
